
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-users"></i><?= $this->title ?>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover" id="<?= $this->tableId ?>">
            <thead>
            <tr>
                <th class="name-column"><?= $this->translate("Nome e cognome"); ?></th>
                <th class="email-column"><?= $this->translate("Email"); ?></th>
                <th class="group-column"><?= $this->translate("Gruppo"); ?></th>
                <th class="status-column"><?= $this->translate("Stato"); ?></th>
                <th class="pin-column"><?= $this->translate("PIN Aziendale"); ?></th>
                <th class="button-column"><?= $this->translate("Azioni"); ?></th>
            </tr>
            </thead>
            <?php /** @var \BusinessCore\Entity\BusinessEmployee $be */
            foreach ($this->list as $be):
                $employee = $be->getEmployee(); ?>
                <tr>
                    <td><?= $employee->getName() . " " . $employee->getSurname(); ?></td>
                    <td><?= $employee->getEmail(); ?></td>
                    <td><?= $be->getGroupName() ?></td>
                    <td><?= $this->businessEmployeeStatus($be->getStatus()); ?></td>
                    <td><?= $employee->getBusinessPin() ?></td>
                    <td>
                        <?php
                        if ($be->isBlocked()) { ?>
                            <a href="<?= $this->url('business/edit/unblock-employee', ['id' => $employee->getId(), 'code' => $this->business->getCode()]); ?>"
                               onclick="return confirm('<?= $this->translate("Sei sicuro di voler sbloccare questo utente?"); ?>')"
                               class="btn-margin validation-btn btn btn-primary btn-xs">
                                <?= $this->translate("Sblocca"); ?>
                            </a>
                            <?php
                            } else if ($be->isApproved()) { ?>
                                <a href="<?= $this->url('business/edit/block-employee', ['id' => $employee->getId(), 'code' => $this->business->getCode()]); ?>"
                                   onclick="return confirm('<?= $this->translate("Sei sicuro di voler bloccare questo utente?"); ?>')"
                                   class="btn-margin btn btn-warning btn-xs">
                                    <?= $this->translate("Blocca"); ?>
                                </a>
                            <?php
                            } else if ($be->isPending()) { ?>
                                <a href="<?= $this->url('business/edit/approve-employee', ['id' => $employee->getId(), 'code' => $this->business->getCode()]); ?>"
                                   onclick="return confirm('<?= $this->translate("Sei sicuro di voler approvare questo utente?"); ?>')"
                                   class="btn-margin btn btn-success btn-xs">
                                    <?= $this->translate("Approva"); ?>
                                </a>
                            <?php
                            }?>
                        <a href="<?= $this->url('business/edit/remove-employee', ['id' => $employee->getId(), 'code' => $this->business->getCode()]); ?>"
                           onclick="return confirm('<?= $this->translate("Sei sicuro di voler eliminare questo utente?"); ?>')"
                           class="btn-margin btn btn-danger btn-xs">
                            <?= $this->translate("Elimina"); ?>
                        </a>
                    </td>
                </tr>
                <?php
            endforeach; ?>
        </table>
    </div>
</div>