<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/customer-business-invoices.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- Header -->
        <h3 class="page-title">
            <?= $this->translate("ELENCO FATTURE"); ?> <small><?= $this->translate("ricerca"); ?></small>
        </h3>
        <div class="page-bar">
        </div>
        <!-- Content -->
        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('partials/flash-messages.phtml', []); ?>
                <!-- Filter container -->
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-inline">
                            <!-- Filter selector -->
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="invoice_number"><?= $this->translate("N° Fattura"); ?></option>
                                    <option value="name"><?= $this->translate("Ragione Sociale"); ?></option>
                                    <option value="fleet_name"><?= $this->translate("Flotta"); ?></option>
                                    <option value="is_business"><?= $this->translate("Azienda"); ?></option>
                                </select>
                            </div>
                            <!-- filter selector -->
                            <!-- Type selector -->
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <!-- type selector -->
                            <!-- Search buttons -->
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search">
                                    <i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?>
                                </button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:void(0);" id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- search buttons -->
                        </div>
                    </div>
                </div>
                <!-- filter container -->
                <hr>
                <!-- Datatable container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco Fatture"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <!-- Table -->
                        <table class="table table-striped table-bordered table-hover" id="js-customer-business-invoices-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("N° Fattura"); ?></th>
                                <th><?= $this->translate("Data"); ?></th>
                                <th><?= $this->translate("Ragione sociale"); ?></th>
                                <th><?= $this->translate("Tipo"); ?></th>
                                <th><?= $this->translate("Totale"); ?></th>
                                <th><?= $this->translate("Download"); ?></th>
                            </tr>
                            </thead>
                        </table>
                        <!-- table -->
                    </div>
                </div>
                <!-- datatable container -->
            </div>
        </div>
        <!-- content -->
    </div>
</div>
