<?php
$form = $this->form->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("AGGIUNGI AZIENDA"); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('business'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla lista"); ?></a>
            </div>
        </div>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
                <?= $this->form()->openTag($form); ?>
                    <div class="row">
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Ragione Sociale"), 'name', $form) ?>
                        </div>
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Domini"), 'domains', $form) ?>
                        </div>
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Email"), 'email', $form) ?>
                        </div>
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Telefono"), 'phone', $form) ?>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Indirizzo"), 'address', $form) ?>
                        </div>
                        <div class="col-lg-2">
                            <?= $this->BusinessForm($this->translate("CAP"), 'zipCode', $form) ?>
                        </div>
                        <div class="col-lg-2">
                            <?= $this->BusinessForm($this->translate("Provincia"), 'province', $form) ?>
                        </div>
                        <div class="col-lg-2">
                            <?= $this->BusinessForm($this->translate("Città"), 'city', $form) ?>
                        </div>
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Fax"), 'fax', $form) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Partita IVA"), 'vatNumber', $form) ?>
                        </div>
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Tipo di pagamento"), 'paymentType', $form) ?>
                        </div>
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Frequenza pagamento"), 'paymentFrequence', $form) ?>
                        </div>
                        <div class="col-lg-3">
                            <?= $this->BusinessForm($this->translate("Controllo email aziendale"), 'businessMailControl', $form) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success"><?= $this->translate("Aggiungi Azienda"); ?></button>
                        </div>
                    </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>