<?php
$this->form->setAttribute('action', $this->url('business/edit/do-edit-details', array('code' => $this->business->getCode())));
$form = $this->form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <?= $this->form()->openTag($form); ?>
        <div class="row">
            <div class="col-lg-3">
                <input type="hidden" name="code" id="code" class="form-control" value="<?= $this->business->getCode(); ?>">
                <?php
                $field = $form->get('name');
                $field->setValue($this->business->getName());
                echo $this->businessFormElement($this->translate("Ragione Sociale"), $field) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('domains');
                $field->setValue(implode(' ', $this->business->getDomains()));
                echo $this->businessFormElement($this->translate("Domini") . ' <small>'.$this->translate("separati da uno spazio").'</small>', $field) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('email');
                $field->setValue($this->business->getEmail());
                echo $this->businessFormElement($this->translate("Email"), $field) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('phone');
                $field->setValue($this->business->getPhone());
                echo $this->businessFormElement($this->translate("Telefono"), $field) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <?php
                $field = $form->get('address');
                $field->setValue($this->business->getAddress());
                echo $this->businessFormElement($this->translate("Indirizzo"), $field) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('zipCode');
                $field->setValue($this->business->getZipCode());
                echo $this->businessFormElement($this->translate("CAP"), $field) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('province');
                $field->setValue($this->business->getProvince());
                echo $this->businessFormElement($this->translate("Provincia"), $field) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('city');
                $field->setValue($this->business->getCity());
                echo $this->businessFormElement($this->translate("Città"), $field) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('fax');
                $field->setValue($this->business->getFax());
                echo $this->businessFormElement($this->translate("Fax"), $field) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <?php
                $field = $form->get('vatNumber');
                $field->setValue($this->business->getVatNumber());
                echo $this->businessFormElement($this->translate("Partita IVA"), $field) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success"><?= $this->translate("Modifica Azienda"); ?></button>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>

    </div>
</div>