<?php
$this->headLink();
$this->headScript()->prependFile($this->basePath() .'/js/spin.min.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("MODIFICA AZIENDA"); ?> <?= $this->business->getName(); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('business'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla lista"); ?></a>
            </div>
        </div>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
                <ul class="nav nav-tabs" id="js-tabs" role="tablist">
                    <li role="presentation" id="menu-info">
                        <a href="<?= $this->url('business/ajax-tab-info', ['code' => $this->business->getCode()]); ?>" data-target="#tab-info" role="tab" data-toggle="tab">
                            <?= $this->translate("Informazioni"); ?>
                        </a>
                    </li>
                    <li role="presentation" id="menu-edit">
                        <a href="<?= $this->url('business/ajax-tab-edit', ['code' => $this->business->getCode()]); ?>" data-target="#tab-edit" role="tab" data-toggle="tab">
                            <?= $this->translate("Modifica"); ?>
                        </a>
                    </li>
                    <li role="presentation" id="menu-params">
                        <a href="<?= $this->url('business/ajax-tab-params', ['code' => $this->business->getCode()]); ?>" data-target="#tab-params" role="tab" data-toggle="tab">
                            <?= $this->translate("Parametri"); ?>
                        </a>
                    </li>
                </ul>

                <div class="tab-content" style="position: relative; min-height: 200px">
                    <div id="spinner-loader"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-info"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-edit"></div>
                    <div role="tabpanel" class="tab-pane" id="tab-params"></div>
                </div>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var target = $('#spinner-loader');
        var spinner = new Spinner().spin(target);

        var tab = '<?= $this->tab ?>';
        var idTab = '#tab-' + tab;
        $('#menu-' + tab).addClass('active');
        $(idTab).addClass('active');

        var href = $(document).find('#js-tabs .active a').attr("href");

        $(idTab).load(href,function(e){
            spinner.stop();
            $('#js-tabs .active a').tab('show');
        });

        $('#js-tabs a').click(function(e) {
            spinner.spin(target);
            var _this = $(this);
            var loadurl = _this.attr('href');
            var targ = _this.attr('data-target');

            $.get(loadurl, function(data) {
                $(targ).html(data);
                spinner.stop();
                _this.tab('show');
            });

            return false;
        });
    });
</script>
