<?php
$this->form->setAttribute('action', $this->url('business/do-edit-details', array('code' => $this->business->getCode())));
$form = $this->form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <?= $this->form()->openTag($form); ?>
        <div class="row">
            <div class="col-lg-3">
                <input type="hidden" name="code" id="code" class="form-control" value="<?= $this->business->getCode(); ?>">

                <div class="form-group">
                    <label for="name"><?= $this->translate("Ragione Sociale"); ?></label>
                    <?php
                    $field = $form->get('name');
                    $field->setValue($this->business->getName());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="domains"><?= $this->translate("Domini"); ?></label> <small><?= $this->translate("separati da uno spazio"); ?></small>
                    <?php
                    $field = $form->get('domains');
                    $domains = $this->business->getDomains();
                    $field->setValue(implode(' ', $domains));
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="email"><?= $this->translate("Email"); ?></label>
                    <?php
                    $field = $form->get('email');
                    $field->setValue($this->business->getEmail());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="phone"><?= $this->translate("Telefono"); ?></label>
                    <?php
                    $field = $form->get('phone');
                    $field->setValue($this->business->getPhone());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="address"><?= $this->translate("Indirizzo"); ?></label>
                    <?php
                    $field = $form->get('address');
                    $field->setValue($this->business->getAddress());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="zip-code"><?= $this->translate("CAP"); ?></label>
                    <?php
                    $field = $form->get('zipCode');
                    $field->setValue($this->business->getZipCode());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="province"><?= $this->translate("Provincia"); ?></label>
                    <?php
                    $field = $form->get('province');
                    $field->setValue($this->business->getProvince());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="city"><?= $this->translate("Città"); ?></label>
                    <?php
                    $field = $form->get('city');
                    $field->setValue($this->business->getCity());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="fax"><?= $this->translate("Fax"); ?></label>
                    <?php
                    $field = $form->get('fax');
                    $field->setValue($this->business->getFax());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <label for="vat-number"><?= $this->translate("Partita IVA"); ?></label>
                    <?php
                    $field = $form->get('vatNumber');
                    $field->setValue($this->business->getVatNumber());
                    echo $this->formElement($field);
                    echo $this->formElementErrors($field, array('class' => 'text-danger list-unstyled'));
                    ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success"><?= $this->translate("Modifica Azienda"); ?></button>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>

    </div>
</div>