<?php
$this->form->setAttribute('action', $this->url('business/edit/do-edit-params', array('code' => $this->business->getCode())));
$form = $this->form->prepare();
?>
<div class="row">
    <div class="col-lg-12">
        <?= $this->form()->openTag($form); ?>
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="code"><?= $this->translate("Codice"); ?></label>
                    <input type="text" name="code" id="code" class="form-control" disabled value="<?= $this->business->getCode(); ?>">
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name"><?= $this->translate("Ragione Sociale"); ?></label>
                    <input type="text" name="name" id="name" class="form-control" disabled value="<?= $this->business->getName(); ?>">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <?= $this->BusinessForm($this->translate("Frequenza pagamento"), 'paymentFrequence', $form, $this->business->getPaymentFrequence()) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <?= $this->BusinessForm($this->translate("Tipo di pagamento"), 'paymentType', $form, $this->business->getPaymentType()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <?= $this->BusinessForm($this->translate("Controllo email aziendale"), 'businessMailControl', $form, $this->business->isBusinessMailControlEnabled()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success"><?= $this->translate("Modifica parametri aziendali"); ?></button>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
