<?php
$this->form->setAttribute('action', $this->url('business/edit/do-edit-details', array('code' => $this->business->getCode())));
$form = $this->form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <?= $this->form()->openTag($form); ?>
        <div class="row">
            <div class="col-lg-3">
                <input type="hidden" name="code" id="code" class="form-control" value="<?= $this->business->getCode(); ?>">
                <?= $this->BusinessForm($this->translate("Ragione Sociale"), 'name', $form, $this->business->getName()) ?>
            </div>
            <div class="col-lg-3">
                <?= $this->BusinessForm($this->translate("Domini"), 'domains', $form, implode(' ', $this->business->getDomains())) ?>
            </div>
            <div class="col-lg-3">
                <?= $this->BusinessForm($this->translate("Email"), 'email', $form, $this->business->getEmail()) ?>
            </div>
            <div class="col-lg-3">
                <?= $this->BusinessForm($this->translate("Telefono"), 'phone', $form, $this->business->getPhone()) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <?= $this->BusinessForm($this->translate("Indirizzo"), 'address', $form, $this->business->getAddress()) ?>
            </div>
            <div class="col-lg-2">
                <?= $this->BusinessForm($this->translate("CAP"), 'zipCode', $form, $this->business->getZipCode()) ?>
            </div>
            <div class="col-lg-2">
                <?= $this->BusinessForm($this->translate("Provincia"), 'province', $form, $this->business->getProvince()) ?>
            </div>
            <div class="col-lg-2">
                <?= $this->BusinessForm($this->translate("Città"), 'city', $form, $this->business->getCity()) ?>
            </div>
            <div class="col-lg-3">
                <?= $this->BusinessForm($this->translate("Fax"), 'fax', $form, $this->business->getFax()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <?= $this->BusinessForm($this->translate("Partita IVA"), 'vatNumber', $form, $this->business->getVatNumber()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success"><?= $this->translate("Modifica Azienda"); ?></button>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>

    </div>
</div>