<?php
?>
<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-md-12">

                <!-- Table -->
                <table id="table" class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th><?= $this->translate("Nome e cognome"); ?></th>
                        <th><?= $this->translate("Email"); ?></th>
                        <th style="width: 100px"><?= $this->translate("Azioni"); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php /** @var \BusinessCore\Entity\Employee $employee */
                    foreach ($this->employees as $employee): ?>
                        <tr>
                            <td><?= $employee->getName() . " " . $employee->getSurname(); ?></td>
                            <td><?= $employee->getEmail(); ?></td>
                            <td>
                                <a href="<?= $this->url('business/remove-employee', ['id' => $employee->getId(), 'code' => $this->business->getCode()]); ?>" onclick="return confirm('Sei sicuro?')" class="validation-btn btn btn-danger btn-xs">
                                    <?= $this->translate("Elimina"); ?>
                                </a>
                                <a href="block" onclick="return confirm('yolo?')" class="validation-btn btn btn-warning btn-xs">
                                    <?= $this->translate("Blocca"); ?>
                                </a>
                            </td>
                        </tr>
                    <?php
                    endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
