<?php
?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="code"><?= $this->translate("Codice"); ?></label>
                    <input type="text" name="code" id="code" class="form-control" disabled value="<?= $this->business->getCode(); ?>">
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name"><?= $this->translate("Ragione Sociale"); ?></label>
                    <input type="text" name="name" id="name" class="form-control" disabled value="<?= $this->business->getName(); ?>">
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="email"><?= $this->translate("Email"); ?></label>
                    <input type="text" name="email" id="email" class="form-control" disabled value="<?= $this->business->getEmail(); ?>">
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="phone"><?= $this->translate("Telefono"); ?></label>
                    <input type="text" name="phone" id="phone" class="form-control" disabled value="<?= $this->business->getPhone(); ?>">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="address"><?= $this->translate("Indirizzo"); ?></label>
                    <input type="text" name="address" id="address" class="form-control" disabled value="<?= $this->business->getAddress(); ?>">
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="zip_code"><?= $this->translate("CAP"); ?></label>
                    <input type="text" name="zip_code" id="zip_code" class="form-control" disabled value="<?= $this->business->getZipCode(); ?>">
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="province"><?= $this->translate("Provincia"); ?></label>
                    <input type="text" name="province" id="province" class="form-control" disabled value="<?= $this->business->getProvince(); ?>">
                </div>
            </div>
            <div class="col-lg-2">
                <div class="form-group">
                    <label for="city"><?= $this->translate("Città"); ?></label>
                    <input type="text" name="city" id="city" class="form-control" disabled value="<?= $this->business->getCity(); ?>">
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="fax"><?= $this->translate("Fax"); ?></label>
                    <input type="text" name="fax" id="fax" class="form-control" disabled value="<?= $this->business->getFax(); ?>">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <input type="hidden" name="tabType" value="info">
                    <label for="domains"><?= $this->translate("Domini associati"); ?></label>
                    <textarea disabled name="domains" rows="4" cols="40"><?= implode("\n", $this->business->getDomains()) ?></textarea>
                </div>
            </div>
        </div>
    </div>
</div>
