<?php
$this->headLink()
        ->appendStylesheet('/css/autocomplete.css');
$this->headScript()
        ->appendFile($this->basePath() . '/js/libs/jquery.autocomplete.min.js')
        ->appendFile($this->basePath() . '/js/penalty.js');

$form = $this->form->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ADDEBITO PENALE/EXTRA"); ?>
        </h3>

        <div class="page-bar">
        </div>

        <?= $this->form()->openTag($form); ?>

        <div class="form-group row">
            <label for="select-business" class="col-sm-2 form-control-label"><?= $this->translate("Seleziona l'azienda"); ?></label>
            <div class="col-sm-10">
                <?php
                $field = $form->get('business');
                echo $this->formElement($field)
                ?>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 form-control-label"><?= $this->translate("Flotta"); ?></label>
            <div class="col-sm-10">
                <select name="fleet" id="fleet" class="form-control">
                    <?php foreach ($this->fleets as $fleet): ?>
                        <option value="<?= $fleet->getId() ?>" <?= $fleet->getId()===1?"selected":"" ?>><?= $fleet->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 form-control-label"><?= $this->translate("Tipologia"); ?></label>
            <div class="col-sm-10">
                <select name="payment_type" id="payment_type" class="form-control">
                    <option value="extra" selected>extra</option>
                    <option value="penality">penality</option>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="amount" class="col-sm-2 form-control-label"><?= $this->translate("Importo"); ?></label>
            <div class="col-sm-10">
                <?php
                $field = $form->get('amount');
                echo $this->formElement($field)
                ?>
            </div>
        </div>
        <div class="form-group row">
            <label for="type" class="col-sm-2 form-control-label"><?= $this->translate("Causale"); ?></label>
            <div class="col-sm-10">
                <?php
                $field = $form->get('reason');
                echo $this->formElement($field)
                ?>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-offset-2 col-sm-2">
                <button type="submit" class="btn btn-secondary"><?= $this->translate("Addebita importo"); ?></button>
            </div>
        </div>
<?= $this->form()->closeTag(); ?>
        <!-- END PAGE CONTENT-->
    </div>
</div>
