<?php
$detailsForm = $this->detailsForm->prepare();
$paramsForm = $this->paramsForm->prepare();
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("AGGIUNGI AZIENDA"); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('business'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla lista"); ?></a>
            </div>
        </div>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
                <?= $this->form()->openTag($detailsForm); ?>
                    <div class="row">
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('name');
                            echo $this->businessFormElement($this->translate("Ragione Sociale"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('domains');
                            echo $this->businessFormElement($this->translate("Domini"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('email');
                            echo $this->businessFormElement($this->translate("Email"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('phone');
                            echo $this->businessFormElement($this->translate("Telefono"), $field) ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('address');
                            echo $this->businessFormElement($this->translate("Indirizzo"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('zipCode');
                            echo $this->businessFormElement($this->translate("CAP"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('province');
                            echo $this->businessFormElement($this->translate("Provincia"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('city');
                            echo $this->businessFormElement($this->translate("Città"), $field) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('fax');
                            echo $this->businessFormElement($this->translate("Fax"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $detailsForm->get('vatNumber');
                            echo $this->businessFormElement($this->translate("Partita IVA"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $paramsForm->get('paymentType');
                            echo $this->businessFormElement($this->translate("Tipo di pagamento"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $paramsForm->get('paymentFrequence');
                            echo $this->businessFormElement($this->translate("Frequenza pagamento"), $field) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <?php
                            $field = $paramsForm->get('invoiceFrequence');
                            echo $this->businessFormElement($this->translate("Frequenza fatturazione"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $paramsForm->get('businessMailControl');
                            echo $this->businessFormElement($this->translate("Controllo email aziendale"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $paramsForm->get('subscriptionFeeCents');
                            $field->setValue(500.00);
                            echo $this->businessFormElement($this->translate("Quota di iscrizione (€)"), $field) ?>
                        </div>
                        <div class="col-lg-3">
                            <?php
                            $field = $paramsForm->get('fleet');
                            echo $this->businessFormElement($this->translate("Flotta"), $field) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success"><?= $this->translate("Aggiungi Azienda"); ?></button>
                        </div>
                    </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>