<?php
/** @var \BusinessCore\Entity\Business $business */
$business = $this->business;

?>
<div class="row">
    <div class="col-lg-12">
        <?php if ($business->hasActiveContract()) { ?>
            <div>
                <h4>
                <?= $this->translate("Contratto numero: ") . $business->getActiveContract()->getId() ; ?>
                </h4>
            </div>
            <div>
                <h4>
                <?= $this->translate("Data creazione: ") . $business->getActiveContract()->getCreatedDate() ; ?>
                </h4>
            </div>
            <a class="btn btn-primary" href="<?= $this->url('business/disable-contract', ['code' => $business->getCode()]); ?>">
                <?= $this->translate("Disabilita contratto"); ?>
            </a>

        <?php } else { ?>
            <div>
                <h2><?= $this->translate("Questa azienda non ha nessun contratto attivo")?></h2>
            </div>

        <?php } ?>

    </div>
</div>
