<?php
?>
<div class="row">
    <div class="col-md-12">

        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

        <?php echo $this->partial('partials/business-employees-table.phtml', [
            'title' => $this->translate("Approvati"),
            'tableId' => 'js-business-employees-table',
            'business' => $this->business,
            'list' => $this->business->getApprovedBusinessEmployees()
        ]); ?>

        <?php echo $this->partial('partials/business-employees-table.phtml', [
            'title' => $this->translate("In attesa di approvazione"),
            'tableId' => 'js-pending-business-employees-table',
            'business' => $this->business,
            'list' => $this->business->getPendingBusinessEmployees()
        ]); ?>

    </div>
</div>

