<?php
$form = $this->form->prepare();
?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-3">
                <?php
                $field = $form->get('name');
                $field->setValue($this->business->getName());
                echo $this->businessFormElement($this->translate("Ragione Sociale"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('domains');
                $field->setValue(implode(' ', $this->business->getDomains()));
                echo $this->businessFormElement($this->translate("Domini"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('email');
                $field->setValue($this->business->getEmail());
                echo $this->businessFormElement($this->translate("Email"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('phone');
                $field->setValue($this->business->getPhone());
                echo $this->businessFormElement($this->translate("Telefono"), $field, true) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <?php
                $field = $form->get('address');
                $field->setValue($this->business->getAddress());
                echo $this->businessFormElement($this->translate("Indirizzo"), $field, true) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('zipCode');
                $field->setValue($this->business->getZipCode());
                echo $this->businessFormElement($this->translate("CAP"), $field, true) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('province');
                $field->setValue($this->business->getProvince());
                echo $this->businessFormElement($this->translate("Provincia"), $field, true) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('city');
                $field->setValue($this->business->getCity());
                echo $this->businessFormElement($this->translate("Città"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('fax');
                $field->setValue($this->business->getFax());
                echo $this->businessFormElement($this->translate("Fax"), $field, true) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <?php
                $field = $form->get('vatNumber');
                $field->setValue($this->business->getVatNumber());
                echo $this->businessFormElement($this->translate("Partita IVA"), $field, true) ?>
            </div>
        </div>
    </div>
</div>
