<?php
$form = $this->form->prepare();
?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label> <?php echo $this->translate("Azienda abilitata");?></label>
                    <input type="text" class="form-control" disabled="disabled" value="<?php echo ($this->business->isEnabled()) ? $this->translate("SI") : $this->translate("NO")?>">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <?php
                $field = $form->get('name');
                $field->setValue($this->business->getName());
                echo $this->businessFormElement($this->translate("Ragione Sociale"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('domains');
                $field->setValue(implode(' ', $this->business->getDomains()));
                echo $this->businessFormElement($this->translate("Domini"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('email');
                $field->setValue($this->business->getEmail());
                echo $this->businessFormElement($this->translate("Email"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('phone');
                $field->setValue($this->business->getPhone());
                echo $this->businessFormElement($this->translate("Telefono"), $field, true) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <?php
                $field = $form->get('address');
                $field->setValue($this->business->getAddress());
                echo $this->businessFormElement($this->translate("Indirizzo"), $field, true) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('zipCode');
                $field->setValue($this->business->getZipCode());
                echo $this->businessFormElement($this->translate("CAP"), $field, true) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('province');
                $field->setValue($this->business->getProvince());
                echo $this->businessFormElement($this->translate("Provincia"), $field, true) ?>
            </div>
            <div class="col-lg-2">
                <?php
                $field = $form->get('city');
                $field->setValue($this->business->getCity());
                echo $this->businessFormElement($this->translate("Città"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <?php
                $field = $form->get('fax');
                $field->setValue($this->business->getFax());
                echo $this->businessFormElement($this->translate("Fax"), $field, true) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <?php
                $field = $form->get('vatNumber');
                $field->setValue($this->business->getVatNumber());
                echo $this->businessFormElement($this->translate("Partita IVA"), $field, true) ?>
            </div>
            <div class="col-lg-3">
                <label> <?php echo $this->translate("Codice destinatario");?></label>
                <input type="text" class="form-control" disabled="disabled" value="<?= $this->business->getRecipientCode() ?>">
            </div>
            <div class="col-lg-3">
                <label> <?php echo $this->translate("PEC");?></label>
                <input type="text" class="form-control" disabled="disabled" value="<?= $this->business->getCem() ?>">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <label> <?php echo $this->translate("Inserimento");?></label>
                <input type="text" class="form-control" disabled="disabled" value="<?php echo (is_null($this->business->getInsertedTs())) ? $this->translate("mai") : $this->business->getInsertedTs()->format("d-m-y H:i:s")?>">
            </div>
            <div class="col-lg-3">
                <label> <?php echo $this->translate("Aggiornamento");?></label>
                <input type="text" class="form-control" disabled="disabled" value="<?php echo (is_null($this->business->getUpdatedTs())) ? $this->translate("mai") : $this->business->getUpdatedTs()->format("d-m-y H:i:s")?>">
            </div>
            <div class="col-lg-3">
                <label> <?php echo $this->translate("Pagamento frequenza (ultimo)");?></label>
                <input type="text" class="form-control" disabled="disabled" value="<?php
                $frequence = $this->business->getPaymentFrequence();
                if($frequence==="weekly") {
                    $frequence = $this->translate("settimanale");
                } else if ($frequence==="fortnightly") {
                    $frequence = $this->translate("quindicinale");
                } else if ($frequence==="monthly") {
                    $frequence = $this->translate("mensile");
                }

                $last = $this->translate("mai");
                if (!is_null($this->business->getLastPaymentExecution())) {
                    $last = $this->business->getLastPaymentExecution()->format("d-m-y H:i:s");
                }
                echo $frequence." (".$last.")";?>">
            </div>
            <div class="col-lg-3">
                <label> <?php echo $this->translate("Fatturazione frequenza (ultimo)");?></label>
                <input type="text" class="form-control" disabled="disabled" value="<?php
                $frequence = $this->business->getInvoiceFrequence();
                if($frequence==="weekly") {
                    $frequence = $this->translate("settimanale");
                } else if ($frequence==="fortnightly") {
                    $frequence = $this->translate("quindicinale");
                } else if ($frequence==="monthly") {
                    $frequence = $this->translate("mensile");
                }

                $last = "mai";
                if (!is_null($this->business->getLastInvoiceExecution())) {
                    $last = $this->business->getLastInvoiceExecution()->format("d-m-y H:i:s");
                }
                echo $frequence." (".$last.")";?>">
            </div>
        </div>
    </div>
</div>
