<?php
$this->headScript()
    ->appendFile($this->basePath() .'/js/business-edit.js');
?>

<div class="row">
    <div class="col-md-8">
        <div class="form-inline">

            <!-- Filter selector -->
            <div class="form-group">
                <select name="column" id="js-column" class="form-control">
                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                </select>
            </div>
            <div class="form-group">
                <input type="text" name="value" value="" class="form-control" id="js-value" placeholder="<?= $this->translate("Filtra..."); ?>">
            </div>

            <!-- Search buttons -->
            <div class="btn-group">
                <button type="button" class="btn green js-search" id="js-search">
                    <i class="fa fa-search"></i> <?= $this->translate("Cerca"); ?>
                </button>
                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a id="js-clear">
                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- search buttons -->

        </div>
    </div>
</div>
<!-- filter container -->

<hr>

<!-- Datatable container -->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cogs"></i><?= $this->translate("Elenco Pagamenti"); ?>
        </div>
    </div>
    <div class="portlet-body">

        <!-- Table -->
        <table class="table table-striped table-bordered table-hover" id="js-business-payments-table">
            <thead>
            <tr>
                <th><?= $this->translate("Data inserimento"); ?></th>
                <th><?= $this->translate("Tipologia"); ?></th>
                <th><?= $this->translate("Importo"); ?></th>
                <th><?= $this->translate("Stato pagamento"); ?></th>
            </tr>
            </thead>
        </table>
        <!-- table -->
    </div>
</div>
