<?php
use BusinessCore\Entity\Base\BusinessPayment;

?>

<div class="row">
    <div class="col-md-12">

        <?= $this->partial('partials/flash-messages.phtml', []); ?>

        <div class="row">
            <div class="col-md-5">
                <div class="form-inline">
                    <div class="form-group">
                        <select name="column" id="js-column" class="form-control">
                            <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                            <option value="type"><?= $this->translate("Tipologia"); ?></option>
                            <option value="status"><?= $this->translate("Stato pagamento"); ?></option>
                        </select>
                    </div>
                    <div class="form-group">
                        <select name="js-payment-type" id="js-payment-type" class="form-control" style="display: none;">
                            <option value="<?= BusinessPayment::TYPE_PACKAGE ?>"><?= $this->translate("Pacchetto minuti"); ?></option>
                            <option value="<?= BusinessPayment::TYPE_TRIP ?>"><?= $this->translate("Corsa"); ?></option>
                            <option value="<?= BusinessPayment::TYPE_EXTRA ?>"><?= $this->translate("Extra/penale"); ?></option>
                            <option value="<?= BusinessPayment::TYPE_SUBSCRIPTION ?>"><?= $this->translate("Sottoscrizione"); ?></option>
                        </select>
                        <select name="js-payment-status" id="js-payment-status" class="form-control" style="display: none;">
                            <option value="<?= BusinessPayment::STATUS_PENDING ?>"><?= $this->translate("Non pagato"); ?></option>
                            <option value="<?= BusinessPayment::STATUS_EXPECTED_PAYED ?>"><?= $this->translate("Pagato ma in attesa di conferma"); ?></option>
                            <option value="<?= BusinessPayment::STATUS_CONFIRMED_PAYED ?>"><?= $this->translate("Pagato"); ?></option>
                            <option value="<?= BusinessPayment::STATUS_INVOICED ?>"><?= $this->translate("Fatturato"); ?></option>
                        </select>
                        <input type="text" name="value" value="" class="form-control" id="js-value"
                               placeholder="<?= $this->translate("Filtra..."); ?>">
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="form-inline">
                    <div class="form-group">
                        <label> <?= $this->translate("Data inserimento da"); ?>: </label>
                        <input class="form-control form-control-inline input-small date-picker" size="16"
                               type="text" id="js-date-from"
                               placeholder="<?= $this->translate("Data inizio"); ?>">
                    </div>
                    <div class="form-group">
                        <label> <?= $this->translate("a"); ?>: </label>
                        <input class="form-control form-control-inline input-small date-picker" size="16"
                               type="text" id="js-date-to"
                               placeholder="<?= $this->translate("Data fine"); ?>">
                    </div>

                    <div class="btn-group">
                        <button type="button" class="btn green js-search" id="js-search"><i
                                class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                        <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i
                                class="fa fa-angle-down"></i></button>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a id="js-clear">
                                    <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- filter container -->

        <hr>

        <!-- Datatable container -->
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?= $this->translate("Elenco Pagamenti"); ?>
                </div>
            </div>
            <div class="portlet-body">

                <!-- Table -->
                <table class="table table-striped table-bordered table-hover" id="js-business-payments-table">
                    <thead>
                    <tr>
                        <th><?= $this->translate("Data inserimento"); ?></th>
                        <th><?= $this->translate("Tipologia"); ?></th>
                        <th><?= $this->translate("Importo"); ?></th>
                        <th><?= $this->translate("Stato pagamento"); ?></th>
                        <th><?= $this->translate("Conferma pagamento"); ?></th>
                        <th><?= $this->translate("Segnato come pagato"); ?></th>
                        <th><?= $this->translate("Dettagli"); ?></th>
                    </tr>
                    </thead>
                </table>
                <!-- table -->
            </div>
        </div>
        <!-- datatable container -->
    </div>
</div>